spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Developers-Cambodia/DEVKH-CONFIGURATION-FILE.git
          search-paths:
            - 'service-config/*service'
          username: LHai-dev
          password: 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
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org:
      springframework:
        cloud:
          config:
            server: DEBUG
    root: info

server:
  port: 8080
