spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SEE
server:
  port: 8086
eureka:
  client:
    service-url:
      #      defaultZone: ${EUREKA_SERVER_ADDRESS}
      defaultZone: http://128.199.204.23:8761/eureka/
