server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://128.199.204.23:5432/spring-cloud-test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
